---
- name: aci.fabric.policies
  hosts: apic
  gather_facts: no
  connection: local
  tasks:
    - name: create aci fabric policies
      include_role:
        name: aci.fabric.policies

- name: aci.access.policies
  hosts: apic
  gather_facts: no
  connection: local
  tasks:
    - name: create aci access policies
      include_role:
        name: aci.access.policies

- name: aci.global.policies
  hosts: apic
  gather_facts: no
  connection: local
  tasks:
    - name: create aci global policies
      include_role:
        name: aci.global.policies

- name: aci.tenant.policies
  hosts: msc
  gather_facts: no
  connection: local
  tasks:
    - name: create aci tenant policies
      include_role:
        name: aci.tenant.policies